### PR TITLE
rename ops.* to array_ops.*

### PR DESCRIPTION
**Pull request by songmeixu**
as Dan required

### CODE REVIEW

**Comment by songmeixu** [comment]
Is it shown that style_check still not work as expect?

And feel the check here is not that handy, may I suggest another way to split it into two parts: pre-commite and enhanced GUI style checking with handy prompt. If you would like wait for a PR for what I suggest, please ignore style_check here.

**Comment by csukuangfj** [comment]
It actually works. Please see the error messages for how to fix the code.

Please refer to https://github.com/danpovey/k2/blob/6cd9beff14ddf5390844fdefead8dc49fe8f4d55/scripts/check_style_cpplint.sh#L7-L16
for how to run the style check locally before opening a pullrequest.

**Comment by csukuangfj** [comment]
> And feel the check here is not that handy, may I suggest another way to split it into two parts: pre-commite and enhanced GUI style checking with handy prompt. If you would like wait for a PR for what I suggest, please ignore style_check here.

Are there any problems with the current approach?

**Comment by songmeixu** [comment]
> It actually works. Please see the error messages for how to fix the code.
> 
> Please refer to
> 
> https://github.com/danpovey/k2/blob/6cd9beff14ddf5390844fdefead8dc49fe8f4d55/scripts/check_style_cpplint.sh#L7-L16
> 
> 
> for how to run the style check locally before opening a pullrequest.

I mean, I just rename files, the same code was passed by style_check just failed here.

**Comment by csukuangfj** [comment]
There are various style problems in the existing code.

The CI checks only the styles of changed/committed files. Other files with style problems are not reported if they are not modified.

**Comment by songmeixu** [comment]
@danpovey please help here. I think either let me wait it happens that another PR to let the whole code actually get checked and passed, or keep ignore it. I would wait for an answer, as it blocks my planned work.

**Comment by csukuangfj** [comment]
The following are the error logs from the CI:
```
~/work/k2/k2
Check last commit
k2/csrc/array_ops.cu:78:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
k2/csrc/array_ops.cu:79:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
k2/csrc/array_ops.cu:83:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
k2/csrc/array_ops.cu:83:  Extra space before ( in function call  [whitespace/parens] [4]
k2/csrc/array_ops.cu:104:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
k2/csrc/array_ops.cu:118:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
k2/csrc/array_ops.cu:118:  Extra space before ( in function call  [whitespace/parens] [4]
k2/csrc/array_ops.cu:127:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
k2/csrc/array_ops.cu:156:  Extra space before ( in function call  [whitespace/parens] [4]
k2/csrc/array_ops.cu:190:  Extra space before ( in function call  [whitespace/parens] [4]
k2/csrc/array_ops.cu:221:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
k2/csrc/array_ops.cu:226:  Extra space before ( in function call  [whitespace/parens] [4]
k2/csrc/array_ops.cu:106:  Add #include <vector> for vector<>  [build/include_what_you_use] [4]
Done processing k2/csrc/array_ops.cu
Total errors found: 13
[FAILED] k2/csrc/array_ops.cu
##[error]Process completed with exit code 1.
```

---

`k2/csrc/array_ops.cu:83:  Extra space before ( in function call  [whitespace/parens] [4]` should be fixed via #148 if you rebase the code.

**Comment by csukuangfj** [comment]
These are small issues. You can merge it if you think it blocks your work.

**Comment by danpovey** [comment]
Merging, this PR was just about renaming so no obligation to fix those style issues.

**Pull request merged**
