### PR TITLE
fix compile error: `stringstream << nullptr` is ambiguous

### PR DESCRIPTION
**Pull request by songmeixu**

### CODE REVIEW

**Comment by danpovey** [comment]
I think it would be better to let it accept nullptr.  Seems it has a type std::nullptr_t.
How about
std::ostream &operator<<(std::ostream &stream, std::nullptr_t null) {
   stream << "(null)";
}

**Comment by qindazhu** [comment]
Tha's why I like maco `K2_CHECK_NOTNULL`, we can implement it with `K2_CHECK(x != nullptr)`, so it would just print `bool` (i.e. the bool value is  `x != nullptr`). There is no need to define `operator<<` for `nullptr`.

**Comment by danpovey** [comment]
Too special-purpose for my taste.  I see no problem with defining operator
<< for nullptr.

**Comment by songmeixu** [comment]
added a specialization for it，passed build, is it ok?

**Comment by danpovey** [comment]
Thanks!  Merging.

**Pull request merged**
