### PR TITLE
fix CUB warnings when using c++11.

### PR DESCRIPTION
**Pull request by csukuangfj**
@qindazhu @danpovey 
please have a review.

### CODE REVIEW

**Comment by qindazhu** [comment]
+1, maybe add some comments to say why we do this?

**Comment by danpovey** [comment]
Guys, actually I dont want to suppress these warnings because it's there for a good reason and will remind us and others that c++11 is not ideal.

**Comment by csukuangfj** [comment]
@danpovey 
I guess you are using GCC 4.9 or 4.8. Are there any reasons not to upgrade gcc to a version >= 5.0 ?

**Comment by danpovey** [comment]
No reason, except that it's a hassle to install.  How can you tell I'm
using that version, and why does it matter?

**Comment by csukuangfj** [comment]
C++ 14 is supported for GCC >= 5.0

GCC 4.8 supports  only C++11, so I think you are using   4.8 <= GCC < 5.0

**Comment by csukuangfj** [comment]
It does not matter since CUB compiles for C++11.

It does matter if you want to avoid the warnings, but you are unable to since your compiler supports only c++11.
> It's causing me problems building it, as the version of gcc here doesn't support that

**Comment by danpovey** [comment]
sorry gonna close this, we can worry uch later about things like suppressing warnings.

**Pull request closed without merging**
